    # Liste des mots inutiles. On veut les supprimer. Exemple : "cherche mes pdf facture" devient : "facture"
blacklist = {
    "cherche",
    "trouve",
    "moi",
    "mon",
    "mes",
    "le",
    "la",
    "les",
    "de",
    "des",
    "du",
    "un",
    "une",
    "et",
    "ou",
    "dans",
    "sur",
    "avec",
    "pour",
    "dossier",
    "fichier",
    "folder",
    "file",
    "ouvre",
    "montre",
}